"""Derive theme presets from the ``vega-themes`` configs bundled in vl-convert.

Many Vega-Lite hosts theme charts by handing ``vega-themes``' ``powerbi``
(light) or ``carbong90`` (dark) straight to their renderer. Hand-reproducing
those in tokens would guarantee a visual regression on the day a host switches.

Instead this generates the presets: the original Vega config is kept **verbatim**
in ``vega_overrides`` so charts render byte-identically to today, while tokens
are extracted from it so the CSS side — KPI tiles, rich tables, the grid — is
themed consistently for the first time.

Run it when vl-convert is upgraded; the output is committed, so nothing at
runtime depends on the ``render`` extra.

    python -m nexcraftviz.theme._generate_presets
"""
from __future__ import annotations

import sys
from pathlib import Path
from typing import Any

import yaml

PRESET_DIR = Path(__file__).parent / "presets"

#: vega-themes name → (our preset name, mode). Adding more is a one-line change.
DERIVE = {
    "powerbi": ("powerbi", "light"),
    "carbong90": ("carbon-g90", "dark"),
}

_LIGHT_DEFAULTS = {
    "surface_alt": "#F6F8FA",
    "border": "#E2E8F0",
    "border_strong": "#CBD5E1",
    "text_primary": "#252423",
    "text_secondary": "#605E5C",
    "text_muted": "#8A8886",
    "text_inverse": "#FFFFFF",
}
_DARK_DEFAULTS = {
    "surface_alt": "#393939",
    "border": "#525252",
    "border_strong": "#6F6F6F",
    "text_primary": "#F4F4F4",
    "text_secondary": "#C6C6C6",
    "text_muted": "#A8A8A8",
    "text_inverse": "#161616",
}


def generate() -> int:
    try:
        import vl_convert as vlc
    except ImportError:
        print("needs the `render` extra: pip install 'nexcraftviz[render]'", file=sys.stderr)
        return 1

    themes = vlc.get_themes()
    for source, (name, mode) in DERIVE.items():
        config = themes.get(source)
        if config is None:
            print(f"skipping {source}: not bundled in this vl-convert", file=sys.stderr)
            continue
        preset = _to_preset(name=name, mode=mode, source=source, config=config)
        path = PRESET_DIR / f"{name}.yaml"
        path.write_text(
            "# GENERATED by `python -m nexcraftviz.theme._generate_presets`.\n"
            f"# Derived from vega-themes `{source}`.\n"
            "# `vega_overrides` is that theme verbatim, so charts render identically;\n"
            "# the tokens above it drive the CSS side. Re-run after a vl-convert bump.\n\n"
            + yaml.safe_dump(preset, sort_keys=False, width=88, allow_unicode=True),
            encoding="utf-8",
        )
        print(f"wrote {path}")
    return 0


def _to_preset(*, name: str, mode: str, source: str, config: dict[str, Any]) -> dict[str, Any]:
    defaults = _DARK_DEFAULTS if mode == "dark" else _LIGHT_DEFAULTS
    axis = config.get("axis") or {}
    background = _colour(config.get("background")) or ("#161616" if mode == "dark" else "#FFFFFF")
    view = config.get("view") or {}
    surface = _colour(view.get("fill")) or background
    primary_mark = _primary_mark_colour(config)

    return {
        "name": name,
        "mode": mode,
        "description": (
            f"Derived from vega-themes `{source}` so charts match hosts that "
            f"render with it; tokens extend it to the non-Vega payloads."
        ),
        "palette": {
            "categorical": _categorical(config),
            "sequential": "blues",
            "diverging": "redblue",
            "ordinal": "blues",
        },
        "semantic": {
            "positive": "#4ADE80" if mode == "dark" else "#15803D",
            "negative": "#F87171" if mode == "dark" else "#B91C1C",
            "warning": "#FBBF24" if mode == "dark" else "#B45309",
            "neutral": defaults["text_muted"],
            "target": defaults["text_muted"],
            "accent": primary_mark,
        },
        "surfaces": {
            "background": background,
            "surface": surface,
            "surface_alt": defaults["surface_alt"],
            "border": defaults["border"],
            "border_strong": defaults["border_strong"],
            "grid": _colour(axis.get("gridColor"))
            or _colour((config.get("axisQuantitative") or {}).get("gridColor"))
            or defaults["border"],
        },
        "text": {
            "primary": _colour(axis.get("titleColor")) or defaults["text_primary"],
            "secondary": _colour(axis.get("labelColor")) or defaults["text_secondary"],
            "muted": defaults["text_muted"],
            "inverse": defaults["text_inverse"],
        },
        "typography": {
            "font_family": _font(config),
            "size_sm": float(axis.get("labelFontSize") or 12),
        },
        "vega_base": "overrides",
        "vega_overrides": config,
    }


def _categorical(config: dict[str, Any]) -> list[str]:
    category = (config.get("range") or {}).get("category")
    if isinstance(category, list):
        return [c for c in category if isinstance(c, str)][:12]
    primary = _primary_mark_colour(config)
    return [primary] if primary else []


def _primary_mark_colour(config: dict[str, Any]) -> str:
    """The theme's own single-series colour.

    Preferred over the first categorical entry: a theme that sets `bar.fill`
    has made an explicit choice about what one series looks like.
    """
    for key, prop in (("bar", "fill"), ("line", "stroke"), ("arc", "fill"), ("rect", "fill")):
        colour = _colour((config.get(key) or {}).get(prop))
        if colour:
            return colour
    category = (config.get("range") or {}).get("category")
    if isinstance(category, list) and category and isinstance(category[0], str):
        return category[0]
    return "#0C8BA6"


def _font(config: dict[str, Any]) -> str:
    for candidate in (
        config.get("font"),
        (config.get("axis") or {}).get("labelFont"),
        (config.get("title") or {}).get("font"),
    ):
        if isinstance(candidate, str) and candidate.strip():
            font = candidate.strip()
            # Themes name a single face; keep a real fallback stack behind it.
            if "," not in font:
                font = f"{font}, system-ui, -apple-system, sans-serif"
            return font
    return "system-ui, -apple-system, sans-serif"


def _colour(value: Any) -> str:
    """Keep only hex colours — `transparent` and named colours are not tokens."""
    if isinstance(value, str) and value.startswith("#"):
        return value
    return ""


if __name__ == "__main__":  # pragma: no cover
    sys.exit(generate())
